### ISSUE TITLE
Doesn't open new code window on linux mint 17.3 - code: bad option: -n

### ISSUE THREAD

**Issue by blamarche** [felipecaputo/git-project-manager#1]
Is anyone else having this issue? It refuses to run the new code instance and I get the following error:

```
[Plugin Host] Error: Command failed: /bin/sh -c code -n "/go/src/github.com/blamarche/assemble-web-chat"
code: bad option: -n

    at ChildProcess.exithandler (child_process.js:215:12)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:817:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)  code: bad option: -n
```

**Comment by felipecaputo** [comment]
Hi @blamarche , I'll check that as soon as I get home.

**Comment by martinpengellyphillips** [comment]
I'm getting a similar error on Windows 10:

```
[Plugin Host] Error: Command failed: C:\WINDOWS\system32\cmd.exe /s /c "code -n "C:\Users\Martin\data\identities\personal\project\lucidity""

    at ChildProcess.exithandler (child_process.js:215:12)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:817:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)  
threadService.ts:199 [Plugin Host] -> null  
```

**Comment by felipecaputo** [comment]
I will fix the behavior for windows tonight but, in Linux there is a problem with the code executing with `child_process`, I've tried with Insiders .deb package and worked

**Comment by felipecaputo** [comment]
I've tried but still not working with linux, it starts a node app instead of code

@martinpengellyphillips Could you please test again in your windows 10 with 0.1.4 ?

**Comment by martinpengellyphillips** [comment]
@felipecaputo Thanks for looking into this. Still getting an error and no project being opened on Windows 10 with 0.1.4

```
[Plugin Host] Error: Command failed: C:\WINDOWS\system32\cmd.exe /s /c "code "C:\Users\Martin\data\identities\personal\project\lucidity" -r"

    at ChildProcess.exithandler (child_process.js:215:12)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:817:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
```

**Comment by martinpengellyphillips** [comment]
Been testing a little more locally and it does appear that when launching code from terminal with `C:\Program Files (x86)\Microsoft VS Code\bin` present in `PATH` then the opening of projects works as expected. That path points to the folder holding `code.cmd` not `Code.exe`. 

When that path is not set then error occurs.  Launching `Code.exe` directly from desktop also exhibits the issue.

**Comment by martinpengellyphillips** [comment]
I've put up a PR #3 with a potential fix for the Windows issue at least.

**Comment by felipecaputo** [comment]
Thx @martinpengellyphillips

**Comment by felipecaputo** [comment]
@blamarche I've tested this a lot, and it seems that in Linux the current code version is having some problems in being executed via `child_process.exec`, `child_process.execFile` and `child_process.spawn`.

I've testes with code-insiders and it works. So with the PR #3 in version 1.5 that I will finish the documentation to release it tonight it will work with code insiders but not with code itself.

Do you believe it solves this issue?

**Comment by blamarche** [comment]
Yes. I have done a little testing and it seems to be a vscode issue :)

Thanks!

**Comment by felipecaputo** [comment]
Version 0.1.5 released
