### ISSUE TITLE
Project folder in settings

### ISSUE THREAD

**Issue by grovina** [felipecaputo/git-project-manager#10]
It'd be nice if we could set a list of project folders in addition to locating git projects within a folder.

**Comment by felipecaputo** [comment]
Hi @grovina, 
If I did not get it wrong, the idea is to have projects paths that are not git repositories in one config to allow you to be able to open it in the same interface.

If it is correct I can add it easily for you

**Comment by grovina** [comment]
Exactly, that'd be useful ;)
