### ISSUE TITLE
Is GPM refresh info popup necessary?

### ISSUE THREAD

**Issue by Tyriar** [felipecaputo/git-project-manager#12]
I find it a bit annoying when I explicitly call refresh and it gives me a popup which I need to manually dismiss.

**Comment by felipecaputo** [comment]
Hi @Tyriar, sorry for taking too long to reply. We were in a hurry here. 

That really makes sense. I'll change it to a simple notification in status bar, just to have a feedback that the refresh finished.

What do you think?

**Comment by Tyriar** [comment]
That's sounds much less intrusive 👍
