### ISSUE TITLE
Error message 'gitProjectManager.openProject' not found

### ISSUE THREAD

**Issue by bencresty** [felipecaputo/git-project-manager#125]
**Describe the bug**
First of all; I really like this extension. It's very useful and speeds up the work flow drastically! I'm working with it for months now with lots of satisfaction, so thanks!

Lately there is a small issue though. Last days the extension sometimes throws an error message when Open Git Project command is used. This wasn't the case before. This happens quite a lot after VS Code just started, but not always. The command seems to work fine once, after a VS Code restart, the error was thrown eearlier, but can happen again after a new VS Code session started.

**To Reproduce**
1. Start a fresh instance of VS Code
2 Ctrl-Shift-P for command palette
3. Run 'GPM: Open Git Project'

**Expected behavior**
As intented: open a list with all git projects

**Screenshots**

![git-project-manager-issue](https://user-images.githubusercontent.com/69322733/142724693-abf53c52-6819-4fec-a4ef-d81950390583.png)

**Desktop (please complete the following information):**
 - OS: Windows 10.0.19042
 - VSCode  flavor (Portable / Insiders / etc): 1.62.3 standard version
 - Version [2018.9]: 1.8.1 (latest version at the moment)

**Comment by felipecaputo** [comment]
Hi @bencresty, I had this error on an early version of the activation events.

I'll take a look today to solve, and I think it might be probably something in the command activation.

Give me a couple hours and I post a feedback here!

And thanks for using and reporting this o/

**Comment by bencresty** [comment]
@felipecaputo thanks!

**Comment by felipecaputo** [comment]
I've found the problem, and later today will probably have the new version with the fix released o/

**Comment by felipecaputo** [comment]
@bencresty I've just release the 1.8.2 with the fix, If it happens again, feel free to open this issue again o/
