### ISSUE TITLE
Don't warn when a folder in gitProjectManager.baseProjectsFolders doesn't exist

### ISSUE THREAD

**Issue by Tyriar** [felipecaputo/git-project-manager#14]
I code on 3 platforms so my `gitProjectManager.baseProjectsFolders` looks similar to this:

```json
  "gitProjectManager.baseProjectsFolders": [
    "C:\\Users\\Daniel\\Documents\\dev",
    "/home/daniel/dev"
  ]
```

I see this when paths don't exist on the current computer:

![image](https://cloud.githubusercontent.com/assets/2193314/18611492/79c9c7c8-7cef-11e6-841e-60862125c659.png)

Related: #13

**Comment by felipecaputo** [comment]
Hi @Tyriar , I belive this can be an option in configuration. Do you think this way it will solve to you?

**Comment by Tyriar** [comment]
Yes this would solve my issue
