### ISSUE TITLE
Triggering the gitProjectManager.openProject command results in a delay

### ISSUE THREAD

**Issue by Tyriar** [felipecaputo/git-project-manager#24]
After using the extension for a week or so now I've noticed myself doing the following:

1. Create a new instance of vscode (ctrl+shift+n)
2. Trigger gitProjectManager.openProject
3. Start typing my search query
4. Press enter

Unfortunately there is a significant delay (~500ms) that occurs after step 2 which means that half of my search query goes in the active file and half in the search field, this means that at step 4 I get the do you want to save dialog.

The way to get around this seems to be to pass a `Thenable<string[]>` to `showQuickPick` instead of a `string[]`, which should show the dialog immediately, allowing successive keystrokes to add to the search query while the git repositories are being loaded.

**Comment by felipecaputo** [comment]
I've removed the promise because of #8 and #9 

But VSCode team fixed the issue and I didn't returned the old code.

Thx again!
