### ISSUE TITLE
Allow exact matches (from start) to always be first

### ISSUE THREAD

**Issue by Tyriar** [felipecaputo/git-project-manager#29]
My issue is that since it's alphabetical now, the top match is not always the best one. Meaning it's less deterministic which project will show up first, I can't simply type "vscode" and press enter:

![image](https://cloud.githubusercontent.com/assets/2193314/19251476/4b012be0-8ef4-11e6-9e71-7693fceff1dc.png)

There are a

Consider the following list of files:
- a
- ab
- b
- bb
- c
- cb

Here are two improvements that would help fix it:
1. Provide option to rank exact matches from start higher, so searching for "b" would yield results like:
   - b
   - bb
   - ab
   - cb
2. Provide option to require matches from the start, so searching "b" would yield:
   - b
   - bb

Option 1 would be ideal for my workflow, displaying the matches from the start first, and then other matches.

**Comment by felipecaputo** [comment]
Hi @Tyriar, I've been trying to figure out a way to do this, but QuickPick doesn't have any callbacks to let us know what did the user typed already.

Option 1 would be great.

I will keep looking for an alternative to find the input text. If I find anything I'll let you know.

**Comment by felipecaputo** [comment]
Hi @Tyriar, I've tried it after the February release and now its seems to work.

If not, feel free to reopen the issue, and thanks a lot for all PRs

**Comment by Tyriar** [comment]
Works great thanks :+1:
