### ISSUE TITLE
Typing before cache is primed does not filter results

### ISSUE THREAD

**Issue by mafredri** [felipecaputo/git-project-manager#30]
If I type in part of a project name before GPM has finished priming its cache, there will be no filtering applied to the result. I need to then type an additional character to trigger the filtering

Reproduction steps:

1. Launch vscode
2. Open GPM (`Cmd+Opt+P`)
3. While GPM is loading, type in e.g. 3 letters from a project
4. Wait until GPM load is complete and GPM shows you all repos
5. Type in 4th letter to see filter applied

PS. Great work on this extension, super useful! 👍

**Comment by felipecaputo** [comment]
Hi @mafredri thanks for your feedback, I'm really happy that you liked the extension.

About the issue I'll take a look at this ASAP, propably at nigh when I get back home.

**Comment by felipecaputo** [comment]
@mafredri It will probably be fixed in next VSCode release, in december

**Comment by mafredri** [comment]
@felipecaputo great, thanks for investigating this =)!

**Comment by felipecaputo** [comment]
I'vre tried and it is working!

**Comment by mafredri** [comment]
Indeed it does, thanks @felipecaputo!
