### ISSUE TITLE
GPM does not pass the correct folder case to VSCode when opening

### ISSUE THREAD

**Issue by klinquist** [felipecaputo/git-project-manager#35]
Latest VSCode on latest OS X.

Whenever I open a project via GPM and the try to debug it, I see the following in my VSCode Debug Console:

`Program path uses differently cased character as file on disk; this might result in breakpoints not being hit.`

...and just like it says, my breakpoints do not get hit.

**Comment by klinquist** [comment]
By the way, it appears the correct case *is* in the dir key of my gpm_projects.json.

**Comment by felipecaputo** [comment]
Hi @klinquist , I'll take a look at this as soon as I get home today. 

As soon as I find it, I'll let you know

**Comment by klinquist** [comment]
Solved. My "baseProjectsFolders" wasn't in the correct case.
