### ISSUE TITLE
Add a command to refresh cache

### ISSUE THREAD

**Issue by unional** [felipecaputo/git-project-manager#37]
Currently there is no way to repopulate the list when cache is enabled. 🌷

**Comment by felipecaputo** [comment]
Hi @unional, have you tried the Refresh Projects command? 

With cache options enabled, it is not working?

![image](https://cloud.githubusercontent.com/assets/7751449/21985798/3734a09a-dbdb-11e6-84bb-8adca6dcecef.png)

**Comment by felipecaputo** [comment]
Closing this issue by inactivity. If the problem persists @unional just comment and I'll try to help again
