### ISSUE TITLE
Feature request: openInNewWindow as a separate command rather than option

### ISSUE THREAD

**Issue by cuth** [felipecaputo/git-project-manager#39]
This is a feature request to remove the option `openInNewWindow` and make two separate commands for opening in a new window or replacing the current window.

This is an excellent plugin for VSCode. Thank you!

**Comment by felipecaputo** [comment]
Hi @cuth, thank you very much for the feedback about the extension. I'm glad to help

I will make asap. I've been working on a complex problem at work and was with almost no time to work here, but things are getting calm now.

I'll try to release this and the other fixes until tomorow!

**Comment by cuth** [comment]
Thanks so much! I just tried it out and it worked perfectly!
