### ISSUE TITLE
Ignore patterns

### ISSUE THREAD

**Issue by chuckhendo** [felipecaputo/git-project-manager#4]
It would be great if we could set the discovery process to ignore certain folders, like node_modules or bower_components so it wouldn't have to crawl them. Would you accept a PR for this?

This may fix the performance issues brought up in #2 if the correct folders are ignored.

**Comment by chuckhendo** [comment]
Apparently you added this in master... disregard! :+1:

**Comment by felipecaputo** [comment]
Hi @chuckhendo, I will release this version today and it really improved a lot the performance.

Thx
