### ISSUE TITLE
Fail Silently on Missing baseProjectFolder

### ISSUE THREAD

**Issue by willpracht** [felipecaputo/git-project-manager#46]
I use this plugin on two different machines (with synced settings via the Settings Sync plugin), both with different directories used for projects.

Example:
```js
[
  '/Users/user1/projects',
  '/Users/user2/projects'
]
```

In previous versions, having an incorrect path in my `baseProjectsFolders` array would fail silently.

So if I was on Machine 1/User 1, it would index those projects properly and then fail silently when it couldn't find the `user2` directory.

With the last update it now fails completely when it can't find all of the folders in the array.

It would be nice to go back to the previous way of handling this.

**Comment by felipecaputo** [comment]
Hi @willpracht, sometime ago, someone asked to avoid warning messages, and proposed a configuration that would hide them. The **warnFoldersNotFound** config is *false* by default.

Could you please check if, changing it to true would fix the problem?

**Comment by felipecaputo** [comment]
@willpracht I'm closing this issue by inactivity. If the problem persists, fell free to reopen it
