### ISSUE TITLE
Does GPM need to search subdirectories?

### ISSUE THREAD

**Issue by xoviat** [felipecaputo/git-project-manager#47]
I have 20 directories, so it should only take a few milliseconds for GPM to list the contents of all of those directories, see a .git folder, and then list projects. However, it takes quite a bit longer because GPM scans the subdirectories of those directories. Is this necessary?

**Comment by felipecaputo** [comment]
Hi @xoviat, I've let it keep searching because I have some projects that have submodules. What do you think about a configuration that allows you to decide this behavior?

**Comment by xoviat** [comment]
Sounds great!

**Comment by felipecaputo** [comment]
@xoviat I've finished the implementation yesterday. I'll just do a little more tests with it today and release ASAP. 

Sorry for taking to long.

**Comment by xoviat** [comment]
@felipecaputo 

I guess I have a different definition of "long." I work on projects where you can expect your pull request to be merged in a month.
