### ISSUE TITLE
command XXX not found

### ISSUE THREAD

**Issue by uMotif-wichura** [felipecaputo/git-project-manager#48]
Hello,

Thank you for a marvellously handy plugin! 

The issue I'm struggling with is that none of the commands seems to be working following an update of VSC. The message I'm getting is 'command 'gitProjectManager.refreshProjects' not found. 

Happy to provide you with any logs, if needed.

**Comment by felipecaputo** [comment]
Hi @uMotif-wichura, you are having this problem on VSCode or in the Insiders version?

I'll take a look to see if I can reproduce this problem as soon as I get home today, and let you know

**Comment by uMotif-wichura** [comment]
Thanks for getting back to me @felipecaputo. It is VSCode.

**Comment by felipecaputo** [comment]
@uMotif-wichura I've tried to reproduce it yesterday but without any success. Could you try to uninstall and install it again and see if the errors persist?

**Comment by uMotif-wichura** [comment]
No luck, I'm afraid; the issue still persists. I uninstalled the extension, restarted VSCode, installed the extension, restarted VSCode again, all to no avail. 

Are there, potentially, any lingering files after the uninstall is complete I could try and remove manually? Let me know if there is any more information I could provide you with.

**Comment by felipecaputo** [comment]
Are you using Mac, Windows or Linux?

Maybe, after uninstalling, delete the extension's folder in you user's folder `~/.vscode/extensions/felipecaputo.git-project-manager-1.3.0` could solve the problem

**Comment by uMotif-wichura** [comment]
Still nothing. I even installed the insiders version of VSCode, and installed the latest version of the extentions (1.3.1). Same issue. 

I'm on a Mac, macOS Sierra.

**Comment by uMotif-wichura** [comment]
I've updated the extension to 1.3.2 and it is working again. Thank you for all your support and a great extension!

**Comment by felipecaputo** [comment]
Great to hear it from you!

Sorry for taking too long.
