### ISSUE TITLE
Insiders not finding folders

### ISSUE THREAD

**Issue by Tyriar** [felipecaputo/git-project-manager#49]
Just saw this:

![image](https://cloud.githubusercontent.com/assets/2193314/25144467/bf68c952-2422-11e7-8346-d6979cac248f.png)

VS Code:

```
Version 1.12.0-insider
Commit 200c4d10571e252fc1b8ead1549d4259b120793c
Date 2017-04-17T06:09:49.840Z
Shell 1.6.6
Renderer 56.0.2924.87
Node 7.4.0
```

Ubuntu 17.04

**Comment by felipecaputo** [comment]
@Tyriar Thanks for the issue, probably some not tested case that break with last refactorying.

I'll look onto it later today.

**Comment by Tyriar** [comment]
@felipecaputo Thanks for fixing the issues 😄
