### ISSUE TITLE
maxDepthRecursion no longer seems to work

### ISSUE THREAD

**Issue by Tyriar** [felipecaputo/git-project-manager#50]
I have the following setup:

```js
{
  "gitProjectManager.baseProjectsFolders": [
    "$HOME/dev",
    "%USERPROFILE%\\Documents\\dev"
  ],
  "gitProjectManager.maxDepthRecursion": 2
}
```

And it seems to be looking very deep in the `"%USERPROFILE%\\Documents\\dev"` folder on Windows as I can see it looking at node_modules in the status bar:

![image](https://cloud.githubusercontent.com/assets/2193314/25285440/1923b224-266f-11e7-836c-085fd3018f26.png)

---

Version details:

- VSCode Version: Code - Insiders 1.12.0-insider (d8fe52b1789a398a7319346b8923d330f7ab1016, 2017-04-19T07:19:29.296Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-svgviewer|cssho|1.4.0|
|EditorConfig|EditorConfig|0.9.3|
|git-project-manager|felipecaputo|1.3.0|
|seti-icons|qinjia|0.1.3|
|theme-glacier|Tyriar|0.0.10|
|theme-sapphire|Tyriar|0.1.0|;

**Comment by felipecaputo** [comment]
@Tyriar Sorry for taking too long to solve this. It was a really busy week at work. o/
