### ISSUE TITLE
Is "didn't opened" correct English?

### ISSUE THREAD

**Issue by DavidDeSloovere** [felipecaputo/git-project-manager#56]
English isn't my primary language, but I think this isn't correct.

![image](https://user-images.githubusercontent.com/352626/29213033-c72d1808-7ea1-11e7-8e60-7193ee0ffd3a.png)

Would "It seems you **haven't** opened any.." be correct?
Also I think project needs to be plural.

Can't we get a native English person to validate?

**Comment by felipecaputo** [comment]
Thanks @DavidDeSloovere, my primary language isn't English too, but that really make sense.

I'll ask that in Stack Exchange English Learners to see if they can help. As soon as I get the answer, I'll update it here

**Comment by DavidDeSloovere** [comment]
I notice I accidentally wrote "Can't we get..." instead of "Can we get...". The latter sound nicer, which I was going for ;-)
