### ISSUE TITLE
Empty project list on Windows

### ISSUE THREAD

**Issue by ntcong** [felipecaputo/git-project-manager#61]
I'm using this config
```{
    "gitProjectManager.baseProjectsFolders": [
        "C:\\test",
        "D:\\Dropbox\\workspace",
        "/Users/ntcong/Dropbox/workspace"
    ],
    "gitProjectManager.storeRepositoriesBetweenSessions": false,
    "gitProjectManager.codePath": [
        "C:\\Program Files\\Microsoft VS Code\\bin\\code.cmd",
        "/usr/local/bin/code"
    ],
    "gitProjectManager.recentProjectsListSize": 5,
    "gitProjectManager.maxDepthRecursion": 2,
    "gitProjectManager.warnIfFolderNotFound": true,
    "gitProjectManager.checkRemoteOrigin": false
}
```

It's working correctly on OSX, but return no entries on Windows (no process bar, no error log).
Is there any way to enable a verbose output so I can know what's going on here.

**Comment by lukehmu** [comment]
Also having this issue on Windows (using the Insider edition of VS Code)

**Comment by felipecaputo** [comment]
Sorry for taking too long. I will add some logs to enable verbose mode to make it easy to. 

Maybe I could try to fix it with a isValidPath before searching for projects

**Comment by ntcong** [comment]
I have cleared the Code folder AppData and it works for a while. Using Open Git Project in Subfolder return correctly "D:\\Dropbox\\workspace"

But after a few restart, it stopped working and subfolder changed to "Dropboxorkspace"

**Comment by felipecaputo** [comment]
@ntcong Thanks for the info. Yesteday I've created a VM to start fixing this. It seems that something is escaping the the `\` in the path after some time. 

I will start changing the way path is built and normalize path to the fs module right from the beginning.

I will problably make a pre-release here in the repo, and it would be great if you could test it!

**Comment by felipecaputo** [comment]
@ntcong Is this problem still happening? Can we close this issue?

**Comment by ntcong** [comment]
I think so, I have used for last few months without problem.
