### ISSUE TITLE
Support mercurial

### ISSUE THREAD

**Issue by janpipek** [felipecaputo/git-project-manager#62]
Hi,
the extension is very useful. Most of my projects are versioned by git by I have a lonely mercurial repo or two. Therefore, I was wondering how difficult it would be to add support for other versioning systems - hg, svn, ... Perhaps they can be recognized by the presence of .hg, .svn, ... directories easily?
Thanks in any case.

**Comment by felipecaputo** [comment]
It would be easy to do. I will take a look and let you know o/

**Comment by janpipek** [comment]
That would be awesome ;-)

**Comment by MortezaT** [comment]
I'd appritiate it if you can make it possible to work on repositories on private servers running `GitLab` or `GitBlit`, etc

**Comment by felipecaputo** [comment]
@MortezaT I'm currently using it with a private gitlab and its working fine, did you found any problem?

**Comment by janpipek** [comment]
I can only confirm that it works for our private GitLab server as well.

**Comment by MortezaT** [comment]
@felipecaputo For me it just shows the loading and nothing else happens, but when I check a folder with github repos it list them all at a glance.

**Comment by felipecaputo** [comment]
@MortezaT could you please collect the logs from the extension, or clone it and run the debug extension?

**Comment by MortezaT** [comment]
@felipecaputo  I checked the logs and found nothing, so it seams the only option is to run the extension in debug mode. Can you walk me through?

**Comment by felipecaputo** [comment]
@MortezaT , sure. You just need to have node version 6+ installed and then:

- clone the repository
- run `npm i` inside the repository folder
- open with VSCode
- press F5 to run debugger

The function that you want is located in `src/GitProjectManager.js`, and is called `showProjectList`

**Comment by felipecaputo** [comment]
@MortezaT, I will just make some tests tonight and finally close this issue and release the next version
