### ISSUE TITLE
Not displaying default remote if it is not named "origin"

### ISSUE THREAD

**Issue by janpipek** [felipecaputo/git-project-manager#63]
I found this randomly when looking for possible causes of #62 .

In your code to display a little info about repos, you explicitly call "git remote show origin". This will fail if the default remote is not called "origin". In such case, it just shows "origin" string.

How to reproduce: Update your .git/config to something like

```
[core]
	repositoryformatversion = 0
	filemode = true
	bare = false
	logallrefupdates = true
[remote "origin_"]
	url = git@github.com:felipecaputo/git-project-manager.git
	fetch = +refs/heads/*:refs/remotes/origin/_*
[branch "master"]
	remote = origin_
	merge = refs/heads/master
```
Perhaps, it's a marginal issue but anyway...

Cheers,
Jan

**Comment by felipecaputo** [comment]
@janpipek thanks for reporting

I'm currently working in 62. I'll fix this as soon as I finish that, what I hope that will happen in next weekend o/
