### ISSUE TITLE
If baseProjectsFolders has only 1 value use it as default.

### ISSUE THREAD

**Issue by timlogemann** [felipecaputo/git-project-manager#64]
I store all my git projects inside `~/projects`. So naturally for me I don't need to select the projects folder as I've provided it to GPM and it's the only one, it would be a nice enhancement if this value would be accepted without needing me to confirm it once more in the dialog.

**Steps to reproduce:**
1. Install GPM
2. install one or several git repositories in a single location e.g: ~/projects/
3. set `"gitProjectManager.baseProjectsFolders": [ "~/Projects/" ],` in the VSCode user prefs
4. Hit `ctrl+alt P`
5. See GPM fail to recognize there's only project folder and hit enter manually to select the projects folder

**Comment by felipecaputo** [comment]
Hi @timlogemann, when you press `Ctrl+Alt+P` it ins't listing all projects inside the `~/Projects` folder?

There are 2 Commands:
  - `Shift + Alt + P`: That asks you for a base folder from your list of base folders to list the projects
  - `Ctrl+Alt+P`: That lists all projects in all base folders

**Comment by felipecaputo** [comment]
@timlogemann Is this still a problem to you?

**Comment by timlogemann** [comment]
I've taken a look, turns out it was a conflicting extension why
`Ctrl+alt+P` did not work. Disabled the other package and now works fine!

You can close this one. Thanks!

**Comment by felipecaputo** [comment]
Thanks for your feedback. If you need anything else, you can open it again!!
