### ISSUE TITLE
Missing entries from list

### ISSUE THREAD

**Issue by Tyriar** [felipecaputo/git-project-manager#66]
Here's a search:

<img width="333" alt="screen shot 2018-03-23 at 4 25 03 pm" src="https://user-images.githubusercontent.com/2193314/37857243-c437443c-2eb6-11e8-91a7-0bd6f627fcb6.png">

But there are extra git repo(s) that should be getting matched:

```
~/dev ❯ find . -type d -name xterm.js
./saamalik/xterm.js
./nikonso/xterm.js
./xtermjs/xterm.js
./other/jdanbrown/xterm.js
./other/FGasper/xterm.js
./other/nikonso/xterm.js
./other/LucianBuzzo/xterm.js
./other/bgw/xterm.js
./other/mofux/xterm.js
./other/npezza93/xterm.js
./amejia1/xterm.js
./Tyriar/xterm.js
./mofux/xterm.js
./chabou/xterm.js
./npezza93/xterm.js
```

---

OS: macOS

Settings:

```
  "gitProjectManager.baseProjectsFolders": [
    "$HOME/dev",
    "%USERPROFILE%\\Documents\\dev"
  ],
```

**Comment by felipecaputo** [comment]
Hi there,

I'll take a look at this today when I get home and let you know

**Comment by felipecaputo** [comment]
It seems to be something with the `checkRemoteOrigin`, but I could not reproduce

Can you turn it off and see if it solves the problem?

If is really this feature I'll fix it ASAP

**Comment by Tyriar** [comment]
@felipecaputo I'll try check when I'm back in the office next week

**Comment by Tyriar** [comment]
This was my bad, I had `"gitProjectManager.maxDepthRecursion": 2` set, changing to 3 fixes it. Sorry about the hassle 😃
