### ISSUE TITLE
Please make gitProjectManager.codePath accept an array of paths

### ISSUE THREAD

**Issue by lhmiranda** [felipecaputo/git-project-manager#7]
I use VS Code both in Windows and Linux and I use code-settings-sync extension so I can sync my settings and extensions between the two systems and it works great except for GPM because I can't set two path for VS Code and using no setting also doesn't works. 
I can set folders for both environments like this and it works nicely:
```
"gitProjectManager.baseProjectsFolders": [
        "/home/xxxxx/repositories",
        "D:\\Repositories"
    ]
```
It would be great if I could do the same for the code executable setting (`gitProjectManager.codePath`) and the extension look in these paths to find Code.

**Comment by felipecaputo** [comment]
Hi @lhmiranda. I will solve this ASAP. Probably with the next version in the end of this week

**Comment by lhmiranda** [comment]
Thanks man, really appreciate the effort! Also thank you for this great extension, fellow brazilian!

**Comment by felipecaputo** [comment]
@lhmiranda I've release it today. It now accepts an array of string, a simple string, or an object that has platform as identifiers and path as values, like you can see in read me

I hope it helps.

Best regards o/

**Comment by felipecaputo** [comment]
@lhmiranda Can you check if it solved your problem please?

**Comment by lhmiranda** [comment]
Yes, it did!
Only for the array mode, tho. I tried using the object where you can set windows and linux paths as properties and it didn't worked at the time.

**Comment by felipecaputo** [comment]
@lhmiranda although now you can use the new vsCode API, it doesn't need to set code path, as it uses internal API.

Glad to be of help o/
