### ISSUE TITLE
Make open in new window smarter

### ISSUE THREAD

**Issue by letheed** [felipecaputo/git-project-manager#71]
AFAIU, currently GPM either opens a new window or replaces the current one.

What I usually want is to open a project in a new window if I already have a project open in this one but open the project in this one if I don't already have a folder open.

Would that be doable?

**Comment by felipecaputo** [comment]
Hi @letheed, I've never tought that way but yes, and I belive it would be a really simple implementation.

The open in new window will be ignored if current window doesn't have any folder open.

Does it seems good for you?

**Comment by letheed** [comment]
Yes, and maybe simple files as well. Might be surprising for users otherwise.
