### ISSUE TITLE
Can't open projects in Insider's Build of VSCode

### ISSUE THREAD

**Issue by brakmic** [felipecaputo/git-project-manager#8]
Hi,

I'm using the Insiders-Build of Code. 

```
Version 1.5.0-insider
Commit 4fc690be310dd02e0ab6529c0b9bf348a8b26a19
Date 2016-09-08T11:04:22.252Z
Shell 0.37.6
Renderer 49.0.2623.75
Node 5.10.0
```

When I try to open one of the projects from my list the following error appears:

```
Error while showing Project list: TypeError: e.done is not a function
```

I've also tried to mitigate the problem by refreshing the project list but the error remained.

Regards,

**Comment by felipecaputo** [comment]
Hi @brakmic, I'll take a look at it tonight. Probably there was some change to the API. 

Thanks for reporting

**Comment by tfuquay** [comment]
Is this potentially related to https://github.com/Microsoft/vscode/issues/11771?

**Comment by felipecaputo** [comment]
@tfuquay Yes, the same call stack and error of Microsoft/vscode#11754

**Comment by wesleycoder** [comment]
Any workarounds possible?

**Comment by sachinofficial** [comment]
Would love to have this fixed soon!

**Comment by wesleycoder** [comment]
It happens with the actual release of vscode too, not just the insiders build.

**Comment by felipecaputo** [comment]
I'll try to fix it in the next hours, sorry for taking to much time. There was an appointment this weekend and I didn't had time to fix it.

**Comment by felipecaputo** [comment]
ShowQuickPick is not working when receive promises. As a side efect, quick pick will not be shown until
  all folders had been searched
