### ISSUE TITLE
'Path does not exist' on project switching

### ISSUE THREAD

**Issue by gmmephisto** [felipecaputo/git-project-manager#88]
Problem:
* After upgrade got an error `Path does not exist` on every project switch. Detail error message: `The path '/~/Documents/projects/<project>' does not seem to exist anymore on disk.`.
* User settings:
    ```json
    "gitProjectManager.baseProjectsFolders": [
        "~/Documents/projects",
        "~/Documents/side-projects"
    ],
    "gitProjectManager.checkRemoteOrigin": false,
    "gitProjectManager.storeRepositoriesBetweenSessions": true,
    ```
* Can be reproduced on clean VSCode install and with absolute paths in `baseProjectsFolders`. `GPM: refresh projects` doesn't help.
* Ubuntu 16.04, VSCode Version: 1.27.2

**Comment by gmmephisto** [comment]
Workaround:
* Comment-out home dir replacing in `getQuickPickList` method in `~/.vscode/extensions/felipecaputo.git-project-manager-1.7.0/src/gitProjectManager.js`:
```js
    getQuickPickList() {
       ...
            if (this.config.displayProjectPath || !this.config.checkRemoteOrigin) {
                let repoDir = repo.dir;
                // if (repoDir.startsWith(homeDir)) {
                //     repoDir = '~/' + repoDir.substring(homeDir.length);
                // }
                description = `${FOLDER} ${repoDir}`;
            }
        ...
        });
    }
```

**Comment by felipecaputo** [comment]
@gmmephisto  thanks for reporting, I'll take a look at this ASAP, probably releasing a oatch version today?

**Comment by felipecaputo** [comment]
1.7.1 released with this workaround. I'll make some tests and write tests for this feature

**Comment by gmmephisto** [comment]
@felipecaputo thanks for quick reply and bugfix version, it works!

**Comment by Tyriar** [comment]
Thanks for the quick fix, just hit this and all I needed to do was update ❤️
