### ISSUE TITLE
Error while showing Project list: TypeError: e.done is not a function

### ISSUE THREAD

**Issue by ksfe** [felipecaputo/git-project-manager#9]
Error while showing Project list: TypeError: e.done is not a function!!  For vs code v1.5.1

**Comment by admiral0** [comment]
Duplicate of #8

**Comment by felipecaputo** [comment]
ShowQuickPick is not working when receive promises.

Version 0.1.14 fixes it, but as a side efect, quick pick will not be shown until all folders had been searched.

**Comment by ksfe** [comment]
Thx all!
